package biisit.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import biisit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.19 12:56:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class BiisitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa39 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa39() throws SailoException {    // Biisit: 39
    Biisit biisit = new Biisit(); 
    Nimi ibe = new Nimi(), melo = new Nimi(); 
    ibe.rekisteroi(); melo.rekisteroi(); 
    assertEquals("From: Biisit line: 44", 0, biisit.getNimia()); 
    biisit.lisaa(ibe); assertEquals("From: Biisit line: 45", 1, biisit.getNimia()); 
    biisit.lisaa(melo); assertEquals("From: Biisit line: 46", 2, biisit.getNimia()); 
    biisit.lisaa(ibe); assertEquals("From: Biisit line: 47", 3, biisit.getNimia()); 
    assertEquals("From: Biisit line: 48", 3, biisit.getNimia()); 
    assertEquals("From: Biisit line: 49", ibe, biisit.annaNimi(0)); 
    assertEquals("From: Biisit line: 50", melo, biisit.annaNimi(1)); 
    assertEquals("From: Biisit line: 51", ibe, biisit.annaNimi(2)); 
    try {
    assertEquals("From: Biisit line: 52", ibe, biisit.annaNimi(3)); 
    fail("Biisit: 52 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    biisit.lisaa(ibe); assertEquals("From: Biisit line: 53", 4, biisit.getNimia()); 
    biisit.lisaa(ibe); assertEquals("From: Biisit line: 54", 5, biisit.getNimia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaTiedot89 */
  @Test
  public void testAnnaTiedot89() {    // Biisit: 89
    Biisit biisit = new Biisit(); 
    Nimi ibe = new Nimi(), melo = new Nimi(), flaco = new Nimi(); 
    ibe.rekisteroi(); melo.rekisteroi(); flaco.rekisteroi(); 
    int id1 = ibe.getTunnusNro(); 
    int id2 = melo.getTunnusNro(); 
    Tieto trap11 = new Tieto(id1); biisit.lisaa(trap11); 
    Tieto trap12 = new Tieto(id1); biisit.lisaa(trap12); 
    Tieto trap21 = new Tieto(id2); biisit.lisaa(trap21); 
    Tieto trap22 = new Tieto(id2); biisit.lisaa(trap22); 
    Tieto trap23 = new Tieto(id2); biisit.lisaa(trap23); 
    List<Tieto> loytyneet; 
    loytyneet = biisit.annaTiedot(flaco); 
    assertEquals("From: Biisit line: 105", 0, loytyneet.size()); 
    loytyneet = biisit.annaTiedot(ibe); 
    assertEquals("From: Biisit line: 107", 2, loytyneet.size()); 
    assertEquals("From: Biisit line: 108", true, loytyneet.get(0) == trap11); 
    assertEquals("From: Biisit line: 109", true, loytyneet.get(1) == trap12); 
    loytyneet = biisit.annaTiedot(melo); 
    assertEquals("From: Biisit line: 111", 3, loytyneet.size()); 
    assertEquals("From: Biisit line: 112", true, loytyneet.get(0) == trap21); 
  } // Generated by ComTest END
}