package fxBiisit.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxBiisit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.16 00:20:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class BiisitMainTest {
}