package biisit.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import biisit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.19 12:58:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class NimiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi49 */
  @Test
  public void testRekisteroi49() {    // Nimi: 49
    Nimi ibe = new Nimi(); 
    assertEquals("From: Nimi line: 51", 0, ibe.getTunnusNro()); 
    ibe.rekisteroi(); 
    Nimi Melo = new Nimi(); 
    Melo.rekisteroi(); 
    int n1 = ibe.getTunnusNro(); 
    int n2 = Melo.getTunnusNro(); 
    assertEquals("From: Nimi line: 57", n1+1, n2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString98 */
  @Test
  public void testToString98() {    // Nimi: 98
    Nimi nimi = new Nimi(); 
    nimi.parse(" 3 | Mazza | slowthai & A$AP Rocky"); 
    assertEquals("From: Nimi line: 101", true, nimi.toString().startsWith("3|Mazza|slowthai & A$AP Rocky")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse128 */
  @Test
  public void testParse128() {    // Nimi: 128
    Nimi nimi = new Nimi(); 
    nimi.parse(" 3 | Mazza | slowthai & A$AP Rocky"); 
    assertEquals("From: Nimi line: 131", 3, nimi.getTunnusNro()); 
    assertEquals("From: Nimi line: 132", true, nimi.toString().startsWith("3|Mazza|slowthai & A$AP Rocky")); 
    nimi.rekisteroi(); 
    int n = nimi.getTunnusNro(); 
    nimi.parse(""+(n+20)); 
    nimi.rekisteroi(); 
    assertEquals("From: Nimi line: 138", n+20+1, nimi.getTunnusNro()); 
  } // Generated by ComTest END
}