package biisit.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import biisit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.23 11:35:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TiedotTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta54 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta54() throws SailoException {    // Tiedot: 54
    Tiedot tietoja = new Tiedot(); 
    Tieto pitsi21 = new Tieto(); pitsi21.taytaTrapTiedoilla(2); 
    Tieto pitsi11 = new Tieto(); pitsi11.taytaTrapTiedoilla(1); 
    Tieto pitsi22 = new Tieto(); pitsi22.taytaTrapTiedoilla(2); 
    Tieto pitsi12 = new Tieto(); pitsi12.taytaTrapTiedoilla(1); 
    Tieto pitsi23 = new Tieto(); pitsi23.taytaTrapTiedoilla(2); 
    String tiedNimi = "testikelmit"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    tietoja.lueTiedostosta(tiedNimi); 
    fail("Tiedot: 66 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    tietoja.lisaa(pitsi21); 
    tietoja.lisaa(pitsi11); 
    tietoja.lisaa(pitsi22); 
    tietoja.lisaa(pitsi12); 
    tietoja.lisaa(pitsi23); 
    tietoja.tallenna(); 
    tietoja = new Tiedot(); 
    tietoja.lueTiedostosta(tiedNimi); 
    Iterator<Tieto> i = tietoja.iterator(); 
    assertEquals("From: Tiedot line: 76", pitsi21.toString(), i.next().toString()); 
    assertEquals("From: Tiedot line: 77", pitsi11.toString(), i.next().toString()); 
    assertEquals("From: Tiedot line: 78", pitsi22.toString(), i.next().toString()); 
    assertEquals("From: Tiedot line: 79", pitsi12.toString(), i.next().toString()); 
    assertEquals("From: Tiedot line: 80", pitsi23.toString(), i.next().toString()); 
    assertEquals("From: Tiedot line: 81", false, i.hasNext()); 
    tietoja.lisaa(pitsi23); 
    tietoja.tallenna(); 
    assertEquals("From: Tiedot line: 84", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Tiedot line: 86", true, fbak.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaTiedot200 */
  @Test
  public void testAnnaTiedot200() {    // Tiedot: 200
    Tiedot tietoja = new Tiedot(); 
    Tieto trap21 = new Tieto(2); tietoja.lisaa(trap21); 
    Tieto trap11 = new Tieto(1); tietoja.lisaa(trap11); 
    Tieto trap22 = new Tieto(2); tietoja.lisaa(trap22); 
    Tieto trap12 = new Tieto(1); tietoja.lisaa(trap12); 
    Tieto trap23 = new Tieto(2); tietoja.lisaa(trap23); 
    Tieto trap51 = new Tieto(5); tietoja.lisaa(trap51); 
    List<Tieto> loytyneet; 
    loytyneet = tietoja.annaTiedot(3); 
    assertEquals("From: Tiedot line: 213", 0, loytyneet.size()); 
    loytyneet = tietoja.annaTiedot(1); 
    assertEquals("From: Tiedot line: 215", 2, loytyneet.size()); 
    assertEquals("From: Tiedot line: 216", true, loytyneet.get(0) == trap11); 
    assertEquals("From: Tiedot line: 217", true, loytyneet.get(1) == trap12); 
    loytyneet = tietoja.annaTiedot(5); 
    assertEquals("From: Tiedot line: 219", 1, loytyneet.size()); 
    assertEquals("From: Tiedot line: 220", true, loytyneet.get(0) == trap51); 
  } // Generated by ComTest END
}